def test_dropdowns(demo):
    demo.goto()
    demo.select_dropdown_value("75%")
    demo.expect_meter_visible()
    demo.select_dropdown_value("25%")
    demo.expect_meter_visible()
    demo.select_dropdown_value("50%")
    demo.expect_meter_visible()
    demo.select_dropdown_value("75%")
    demo.expect_meter_visible()
    demo.select_dropdown_value("100%")
    demo.expect_meter_visible()
